### ISSUE TITLE
Updating `vuetify.config.ts` has no effect

### ISSUE THREAD

**Issue by kingyue737** [userquin/vuetify-nuxt-module#129]
repro: https://stackblitz.com/edit/github-fi3r47

Change default button color from `red` to `white`, nothing happened even though the console printed that the vuetify configuration has reloaded. I need to restart nuxt to make changes take effect.

**Comment by userquin** [comment]
Seems a bug, maybe we need to invalidate styles...

**Comment by davidstackio** [comment]
I'm also experiencing this. I have to restart nuxt to see the changes.

**Comment by userquin** [comment]
With the current state of vite-node, we cannot reload virtual modules in the server. After a few hours of testing there is no way, the client working properly but getting hydration missmatch warning/error:

The client is fine, but the server cannot use new configuration since the virtual module not being invalidated:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/bcc41d65-a438-4525-86ee-d64a745ec125)

This is the problem:

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/fc620e48-9230-4db0-94df-b281b58a4381)

**Comment by userquin** [comment]
I'll try another approach, if not working the only thing we can do is restart nuxt dev server when SSR enabled.

**Comment by userquin** [comment]
OK, found the problem and fixing it in my local...

**Comment by userquin** [comment]
Current state of vite-node cannot reload modules in the server, I need to do some more tests but there is no way to reload them, a temporal workaround is to restart nuxt server.
