### ISSUE TITLE
 Hybrid rendering: Cannot destructure property 'firstRequest' of 'state.value' as it is undefined

### ISSUE THREAD

**Issue by kingyue737** [userquin/vuetify-nuxt-module#169]
Reproduction: https://stackblitz.com/edit/github-fi3r47-xug7re

The reproduction project is SSR but one of the routes is set with `{ ssr: false }`.
This error occurs when I navigate to this route via address bar.

Step:
1. Open the repro link
2. Append `/bug` in webcontainer address bar after the dev server started
3. You will see `500 Cannot destructure property 'firstRequest' of 'state.value' as it is undefined.`

**Comment by userquin** [comment]
@kingyue737 I can protect the code against the error, I have no idea what's happening since we can't register anything, check [vuetify-client-hints.client.ts](https://github.com/userquin/vuetify-nuxt-module/blob/main/src/runtime/plugins/vuetify-client-hints.client.ts)

![imagen](https://github.com/userquin/vuetify-nuxt-module/assets/6311119/0858f21c-972f-4447-a978-b06df678d2e8)

**Comment by userquin** [comment]
@kingyue737 I guess I've found the way to hack it via Nitro plugin detecting non SSR page request and sending server-timing http headers to the client, rn the new `/no-ssr`  page in the playground works on page refresh, I need to expose the configuration to the Nitro Plugin and finish some logic in the client to restore the theme

**Comment by userquin** [comment]
@kingyue737 added nitro plugin and updated SSR client hints logic to restore theme-color, working fine.

If you want to test it, you can fork this repo and checkout the PR branch, instructions in the PR to run the playground.

**Comment by userquin** [comment]
@kingyue737 should be fixed in `v0.9.1`, the fix didn't require a nitro plugin, the data can be configured in the client plugin
